# This file is part of Workflow.
# Copyright (C) 2014 CERN.
#
# Workflow is free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see COPYING.txt file for
# more details.

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install --upgrade pip  --use-mirrors
  - pip install pytest pytest-pep8 pytest-cov pytest-cache --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install -e .[docs]

script:
  - sphinx-build -qnNW docs docs/_build/html
  - python setup.py test

after_success:
  - coveralls

notifications:
  email: false
